version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: arcora-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}

    #ports:
      #- "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - arcora-network

    restart: always

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  flask-app:
    build:
      context: .
    container_name: arcora-web

    ports:
      - "5000:5000"

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - arcora-network

    restart: always


volumes:
  mysql_data:


networks:
  arcora-network:
